name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        enable-zio-http: [yes, no]
        enable-akka-http: [yes, no]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup JDK (temurin@17)
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Cache sbt
      uses: actions/cache@v2
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - name: Run | enable_zio_http=${{ matrix.enable-zio-http}}, enable_akka_http=${{ matrix.enable-akka-http }}
      run: sbt ';set g8Properties in g8 in Test ~= { _ ++ Map("enable_zio_http" -> "${{ matrix.enable-zio-http }}", "enable_akka_http" -> "${{ matrix.enable-akka-http }}") }; test'

